/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/

package com.testmssqlimport.adventureworks2014.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.testmssqlimport.adventureworks2014.service.EmployeePayHistoryService;
import org.joda.time.LocalDateTime;
import org.springframework.web.bind.annotation.RequestBody;


import java.io.*;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.hibernate.TypeMismatchException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartHttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.util.WMMultipartUtils;
import com.wavemaker.runtime.util.WMRuntimeUtils;
import com.wavemaker.runtime.file.model.DownloadResponse;
import com.wordnik.swagger.annotations.*;

import com.testmssqlimport.adventureworks2014.*;
import com.testmssqlimport.adventureworks2014.service.*;


/**
 * Controller object for domain model class EmployeePayHistory.
 * @see com.testmssqlimport.adventureworks2014.EmployeePayHistory
 */

@RestController(value = "AdventureWorks2014.EmployeePayHistoryController")
@Api(value = "/AdventureWorks2014/EmployeePayHistory", description = "Exposes APIs to work with EmployeePayHistory resource.")
@RequestMapping("/AdventureWorks2014/EmployeePayHistory")
public class EmployeePayHistoryController {

    private static final Logger LOGGER = LoggerFactory.getLogger(EmployeePayHistoryController.class);

	@Autowired
	@Qualifier("AdventureWorks2014.EmployeePayHistoryService")
	private EmployeePayHistoryService employeePayHistoryService;


	@RequestMapping(value = "/search", method = RequestMethod.POST)
	@ApiOperation(value = "Returns the list of EmployeePayHistory instances matching the search criteria.")
	public Page<EmployeePayHistory> findEmployeePayHistorys( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
		LOGGER.debug("Rendering EmployeePayHistorys list");
		return employeePayHistoryService.findAll(queryFilters, pageable);
	}

	@RequestMapping(value = "/", method = RequestMethod.GET)
	@ApiOperation(value = "Returns the list of EmployeePayHistory instances.")
	public Page<EmployeePayHistory> getEmployeePayHistorys(Pageable pageable) {
		LOGGER.debug("Rendering EmployeePayHistorys list");
		return employeePayHistoryService.findAll(pageable);
	}

	@RequestMapping(value = "/count", method = RequestMethod.GET)
	@ApiOperation(value = "Returns the total count of EmployeePayHistory instances.")
	public Long countAllEmployeePayHistorys() {
		LOGGER.debug("counting EmployeePayHistorys");
		Long count = employeePayHistoryService.countAll();
		return count;
	}

	@RequestMapping(value = "/composite-id", method = RequestMethod.GET)
	@ApiOperation(value = "Returns the EmployeePayHistory instance associated with the given composite-id.")
	public EmployeePayHistory getEmployeePayHistory( @RequestParam("businessEntityId") Integer businessEntityId, @RequestParam("rateChangeDate") LocalDateTime rateChangeDate)
	 throws EntityNotFoundException {
	    EmployeePayHistoryId temp = new EmployeePayHistoryId();
	    temp.setBusinessEntityId(businessEntityId);
	    temp.setRateChangeDate(rateChangeDate);
		LOGGER.debug("Getting EmployeePayHistory with id: {}" , temp);
		EmployeePayHistory instance = employeePayHistoryService.findById(temp);
		LOGGER.debug("EmployeePayHistory details with id: {}" , instance);
		return instance;
	}
	@RequestMapping(value = "/composite-id", method = RequestMethod.DELETE)
	@ApiOperation(value = "Deletes the EmployeePayHistory instance associated with the given composite-id.")
	public boolean deleteEmployeePayHistory( @RequestParam("businessEntityId") Integer businessEntityId, @RequestParam("rateChangeDate") LocalDateTime rateChangeDate)throws EntityNotFoundException {
	    EmployeePayHistoryId temp = new EmployeePayHistoryId();
        temp.setBusinessEntityId(businessEntityId);
        temp.setRateChangeDate(rateChangeDate);
		LOGGER.debug("Deleting EmployeePayHistory with id: {}" , temp);
		EmployeePayHistory deleted = employeePayHistoryService.delete(temp);
		return deleted != null;
	}

	@RequestMapping(value = "/composite-id", method = RequestMethod.PUT)
	@ApiOperation(value = "Updates the EmployeePayHistory instance associated with the given composite-id.")
	public EmployeePayHistory editEmployeePayHistory( @RequestParam("businessEntityId") Integer businessEntityId, @RequestParam("rateChangeDate") LocalDateTime rateChangeDate, @RequestBody EmployeePayHistory instance) throws EntityNotFoundException {
	    EmployeePayHistoryId temp = new EmployeePayHistoryId();
         temp.setBusinessEntityId(businessEntityId);
         temp.setRateChangeDate(rateChangeDate);
        employeePayHistoryService.delete(temp);
        instance = employeePayHistoryService.create(instance);
	    LOGGER.debug("EmployeePayHistory details with id is updated: {}" , instance);
		return instance;
	}

	@RequestMapping(value = "/", method = RequestMethod.POST)
	@ApiOperation(value = "Creates a new EmployeePayHistory instance.")
	public EmployeePayHistory createEmployeePayHistory(@RequestBody EmployeePayHistory instance) {
		LOGGER.debug("Create EmployeePayHistory with information: {}" , instance);
		instance = employeePayHistoryService.create(instance);
		LOGGER.debug("Created EmployeePayHistory with information: {}" , instance);
	    return instance;
	}

	/**
	 * This setter method should only be used by unit tests
	 * 
	 * @param service
	 */
	protected void setEmployeePayHistoryService(EmployeePayHistoryService service) {
		this.employeePayHistoryService = service;
	}
}

