/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/

package com.testmssqlimport.adventureworks2014.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.testmssqlimport.adventureworks2014.service.TableNameService;


import java.io.*;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.hibernate.TypeMismatchException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartHttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.util.WMMultipartUtils;
import com.wavemaker.runtime.util.WMRuntimeUtils;
import com.wavemaker.runtime.file.model.DownloadResponse;
import com.wordnik.swagger.annotations.*;

import com.testmssqlimport.adventureworks2014.*;
import com.testmssqlimport.adventureworks2014.service.*;


/**
 * Controller object for domain model class TableName.
 * @see com.testmssqlimport.adventureworks2014.TableName
 */

@RestController(value = "AdventureWorks2014.TableNameController")
@Api(value = "/AdventureWorks2014/TableName", description = "Exposes APIs to work with TableName resource.")
@RequestMapping("/AdventureWorks2014/TableName")
public class TableNameController {

    private static final Logger LOGGER = LoggerFactory.getLogger(TableNameController.class);

	@Autowired
	@Qualifier("AdventureWorks2014.TableNameService")
	private TableNameService tableNameService;


	@RequestMapping(value = "/search", method = RequestMethod.POST)
	@ApiOperation(value = "Returns the list of TableName instances matching the search criteria.")
	public Page<TableName> findTableNames( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
		LOGGER.debug("Rendering TableNames list");
		return tableNameService.findAll(queryFilters, pageable);
	}

	@RequestMapping(value = "/", method = RequestMethod.GET)
	@ApiOperation(value = "Returns the list of TableName instances.")
	public Page<TableName> getTableNames(Pageable pageable) {
		LOGGER.debug("Rendering TableNames list");
		return tableNameService.findAll(pageable);
	}

	@RequestMapping(value = "/count", method = RequestMethod.GET)
	@ApiOperation(value = "Returns the total count of TableName instances.")
	public Long countAllTableNames() {
		LOGGER.debug("counting TableNames");
		Long count = tableNameService.countAll();
		return count;
	}


    @RequestMapping(value = "/{id:.+}", method = RequestMethod.GET)
    @ApiOperation(value = "Returns the TableName instance associated with the given id.")
    public TableName getTableName(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Getting TableName with id: {}" , id);
        TableName instance = tableNameService.findById(id);
        LOGGER.debug("TableName details with id: {}" , instance);
        return instance;
    }
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.DELETE)
    @ApiOperation(value = "Deletes the TableName instance associated with the given id.")
    public boolean deleteTableName(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Deleting TableName with id: {}" , id);
        TableName deleted = tableNameService.delete(id);
        return deleted != null;
    }

    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @ApiOperation(value = "Updates the TableName instance associated with the given id.")
    public TableName editTableName(@PathVariable("id") Integer id, @RequestBody TableName instance) throws EntityNotFoundException {
        LOGGER.debug("Editing TableName with id: {}" , instance.getColumn1());
        instance.setColumn1(id);
        instance = tableNameService.update(instance);
        LOGGER.debug("TableName details with id: {}" , instance);
        return instance;
    }




	@RequestMapping(value = "/", method = RequestMethod.POST)
	@ApiOperation(value = "Creates a new TableName instance.")
	public TableName createTableName(@RequestBody TableName instance) {
		LOGGER.debug("Create TableName with information: {}" , instance);
		instance = tableNameService.create(instance);
		LOGGER.debug("Created TableName with information: {}" , instance);
	    return instance;
	}

	/**
	 * This setter method should only be used by unit tests
	 * 
	 * @param service
	 */
	protected void setTableNameService(TableNameService service) {
		this.tableNameService = service;
	}
}

