/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/

package com.testmssqlimport.adventureworks2014;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * TableName generated by hbm2java
 */
@Entity
@Table(name="`table_name`"
    ,schema="HumanResources"
)

public class TableName  implements java.io.Serializable {

    private Integer column1;

    public TableName() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`column_1`", nullable=false)
    public Integer getColumn1() {
        return this.column1;
    }
    
    public void setColumn1(Integer column1) {
        this.column1 = column1;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof TableName) )
		    return false;

		 TableName that = (TableName) o;

		 return ( (this.getColumn1()==that.getColumn1()) || ( this.getColumn1()!=null && that.getColumn1()!=null && this.getColumn1().equals(that.getColumn1()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getColumn1() == null ? 0 : this.getColumn1().hashCode() );

         return result;
    }


}

