/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/

package com.testmssqlimport.adventureworks2014;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Embeddable;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * VemployeeId generated by hbm2java
 */
@Embeddable
public class VemployeeId  implements java.io.Serializable {

    private Integer businessEntityId;
    private String title;
    private String firstName;
    private String middleName;
    private String lastName;
    private String suffix;
    private String jobTitle;
    private String phoneNumber;
    private String phoneNumberType;
    private String emailAddress;
    private Integer emailPromotion;
    private String addressLine1;
    private String addressLine2;
    private String city;
    private String stateProvinceName;
    private String postalCode;
    private String countryRegionName;
    private String additionalContactInfo;

    public VemployeeId() {
    }


    public Integer getBusinessEntityId() {
        return this.businessEntityId;
    }
    
    public void setBusinessEntityId(Integer businessEntityId) {
        this.businessEntityId = businessEntityId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getSuffix() {
        return this.suffix;
    }
    
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getPhoneNumberType() {
        return this.phoneNumberType;
    }
    
    public void setPhoneNumberType(String phoneNumberType) {
        this.phoneNumberType = phoneNumberType;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public Integer getEmailPromotion() {
        return this.emailPromotion;
    }
    
    public void setEmailPromotion(Integer emailPromotion) {
        this.emailPromotion = emailPromotion;
    }
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getStateProvinceName() {
        return this.stateProvinceName;
    }
    
    public void setStateProvinceName(String stateProvinceName) {
        this.stateProvinceName = stateProvinceName;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getCountryRegionName() {
        return this.countryRegionName;
    }
    
    public void setCountryRegionName(String countryRegionName) {
        this.countryRegionName = countryRegionName;
    }
    public String getAdditionalContactInfo() {
        return this.additionalContactInfo;
    }
    
    public void setAdditionalContactInfo(String additionalContactInfo) {
        this.additionalContactInfo = additionalContactInfo;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof VemployeeId) )
		    return false;

		 VemployeeId that = (VemployeeId) o;

         return ( (this.getBusinessEntityId()==that.getBusinessEntityId()) || ( this.getBusinessEntityId()!=null && that.getBusinessEntityId()!=null && this.getBusinessEntityId().equals(that.getBusinessEntityId()) ) )
 && ( (this.getTitle()==that.getTitle()) || ( this.getTitle()!=null && that.getTitle()!=null && this.getTitle().equals(that.getTitle()) ) )
 && ( (this.getFirstName()==that.getFirstName()) || ( this.getFirstName()!=null && that.getFirstName()!=null && this.getFirstName().equals(that.getFirstName()) ) )
 && ( (this.getMiddleName()==that.getMiddleName()) || ( this.getMiddleName()!=null && that.getMiddleName()!=null && this.getMiddleName().equals(that.getMiddleName()) ) )
 && ( (this.getLastName()==that.getLastName()) || ( this.getLastName()!=null && that.getLastName()!=null && this.getLastName().equals(that.getLastName()) ) )
 && ( (this.getSuffix()==that.getSuffix()) || ( this.getSuffix()!=null && that.getSuffix()!=null && this.getSuffix().equals(that.getSuffix()) ) )
 && ( (this.getJobTitle()==that.getJobTitle()) || ( this.getJobTitle()!=null && that.getJobTitle()!=null && this.getJobTitle().equals(that.getJobTitle()) ) )
 && ( (this.getPhoneNumber()==that.getPhoneNumber()) || ( this.getPhoneNumber()!=null && that.getPhoneNumber()!=null && this.getPhoneNumber().equals(that.getPhoneNumber()) ) )
 && ( (this.getPhoneNumberType()==that.getPhoneNumberType()) || ( this.getPhoneNumberType()!=null && that.getPhoneNumberType()!=null && this.getPhoneNumberType().equals(that.getPhoneNumberType()) ) )
 && ( (this.getEmailAddress()==that.getEmailAddress()) || ( this.getEmailAddress()!=null && that.getEmailAddress()!=null && this.getEmailAddress().equals(that.getEmailAddress()) ) )
 && ( (this.getEmailPromotion()==that.getEmailPromotion()) || ( this.getEmailPromotion()!=null && that.getEmailPromotion()!=null && this.getEmailPromotion().equals(that.getEmailPromotion()) ) )
 && ( (this.getAddressLine1()==that.getAddressLine1()) || ( this.getAddressLine1()!=null && that.getAddressLine1()!=null && this.getAddressLine1().equals(that.getAddressLine1()) ) )
 && ( (this.getAddressLine2()==that.getAddressLine2()) || ( this.getAddressLine2()!=null && that.getAddressLine2()!=null && this.getAddressLine2().equals(that.getAddressLine2()) ) )
 && ( (this.getCity()==that.getCity()) || ( this.getCity()!=null && that.getCity()!=null && this.getCity().equals(that.getCity()) ) )
 && ( (this.getStateProvinceName()==that.getStateProvinceName()) || ( this.getStateProvinceName()!=null && that.getStateProvinceName()!=null && this.getStateProvinceName().equals(that.getStateProvinceName()) ) )
 && ( (this.getPostalCode()==that.getPostalCode()) || ( this.getPostalCode()!=null && that.getPostalCode()!=null && this.getPostalCode().equals(that.getPostalCode()) ) )
 && ( (this.getCountryRegionName()==that.getCountryRegionName()) || ( this.getCountryRegionName()!=null && that.getCountryRegionName()!=null && this.getCountryRegionName().equals(that.getCountryRegionName()) ) )
 && ( (this.getAdditionalContactInfo()==that.getAdditionalContactInfo()) || ( this.getAdditionalContactInfo()!=null && that.getAdditionalContactInfo()!=null && this.getAdditionalContactInfo().equals(that.getAdditionalContactInfo()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getBusinessEntityId() == null ? 0 : this.getBusinessEntityId().hashCode() );
         result = 37 * result + ( getTitle() == null ? 0 : this.getTitle().hashCode() );
         result = 37 * result + ( getFirstName() == null ? 0 : this.getFirstName().hashCode() );
         result = 37 * result + ( getMiddleName() == null ? 0 : this.getMiddleName().hashCode() );
         result = 37 * result + ( getLastName() == null ? 0 : this.getLastName().hashCode() );
         result = 37 * result + ( getSuffix() == null ? 0 : this.getSuffix().hashCode() );
         result = 37 * result + ( getJobTitle() == null ? 0 : this.getJobTitle().hashCode() );
         result = 37 * result + ( getPhoneNumber() == null ? 0 : this.getPhoneNumber().hashCode() );
         result = 37 * result + ( getPhoneNumberType() == null ? 0 : this.getPhoneNumberType().hashCode() );
         result = 37 * result + ( getEmailAddress() == null ? 0 : this.getEmailAddress().hashCode() );
         result = 37 * result + ( getEmailPromotion() == null ? 0 : this.getEmailPromotion().hashCode() );
         result = 37 * result + ( getAddressLine1() == null ? 0 : this.getAddressLine1().hashCode() );
         result = 37 * result + ( getAddressLine2() == null ? 0 : this.getAddressLine2().hashCode() );
         result = 37 * result + ( getCity() == null ? 0 : this.getCity().hashCode() );
         result = 37 * result + ( getStateProvinceName() == null ? 0 : this.getStateProvinceName().hashCode() );
         result = 37 * result + ( getPostalCode() == null ? 0 : this.getPostalCode().hashCode() );
         result = 37 * result + ( getCountryRegionName() == null ? 0 : this.getCountryRegionName().hashCode() );
         result = 37 * result + ( getAdditionalContactInfo() == null ? 0 : this.getAdditionalContactInfo().hashCode() );

         return result;
    }


}

