/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/

package com.testmssqlimport.adventureworks2014;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * VjobCandidate generated by hbm2java
 */
@Entity
@Table(name="`vJobCandidate`"
    ,schema="HumanResources"
)
@IdClass(value=VjobCandidateId.class)
public class VjobCandidate  implements java.io.Serializable {

    private Integer jobCandidateId;
    private Integer businessEntityId;
    private String name_prefix;
    private String name_first;
    private String name_middle;
    private String name_last;
    private String name_suffix;
    private String skills;
    private String addr_type;
    private String addr_loc_countryRegion;
    private String addr_loc_state;
    private String addr_loc_city;
    private String addr_postalCode;
    private String email;
    private String webSite;


@Type(type="DateTime")
    private LocalDateTime modifiedDate;

    public VjobCandidate() {
    }


    @Id 
    

    @Column(name="`JobCandidateID`", nullable=false, insertable=false, updatable=false)
    public Integer getJobCandidateId() {
        return this.jobCandidateId;
    }
    
    public void setJobCandidateId(Integer jobCandidateId) {
        this.jobCandidateId = jobCandidateId;
    }
    @Id 
    

    @Column(name="`BusinessEntityID`", insertable=false, updatable=false)
    public Integer getBusinessEntityId() {
        return this.businessEntityId;
    }
    
    public void setBusinessEntityId(Integer businessEntityId) {
        this.businessEntityId = businessEntityId;
    }
    @Id 
    

    @Column(name="`Name.Prefix`", insertable=false, updatable=false)
    public String getName_prefix() {
        return this.name_prefix;
    }
    
    public void setName_prefix(String name_prefix) {
        this.name_prefix = name_prefix;
    }
    @Id 
    

    @Column(name="`Name.First`", insertable=false, updatable=false)
    public String getName_first() {
        return this.name_first;
    }
    
    public void setName_first(String name_first) {
        this.name_first = name_first;
    }
    @Id 
    

    @Column(name="`Name.Middle`", insertable=false, updatable=false)
    public String getName_middle() {
        return this.name_middle;
    }
    
    public void setName_middle(String name_middle) {
        this.name_middle = name_middle;
    }
    @Id 
    

    @Column(name="`Name.Last`", insertable=false, updatable=false)
    public String getName_last() {
        return this.name_last;
    }
    
    public void setName_last(String name_last) {
        this.name_last = name_last;
    }
    @Id 
    

    @Column(name="`Name.Suffix`", insertable=false, updatable=false)
    public String getName_suffix() {
        return this.name_suffix;
    }
    
    public void setName_suffix(String name_suffix) {
        this.name_suffix = name_suffix;
    }
    @Id 
    

    @Column(name="`Skills`", insertable=false, updatable=false)
    public String getSkills() {
        return this.skills;
    }
    
    public void setSkills(String skills) {
        this.skills = skills;
    }
    @Id 
    

    @Column(name="`Addr.Type`", insertable=false, updatable=false)
    public String getAddr_type() {
        return this.addr_type;
    }
    
    public void setAddr_type(String addr_type) {
        this.addr_type = addr_type;
    }
    @Id 
    

    @Column(name="`Addr.Loc.CountryRegion`", insertable=false, updatable=false)
    public String getAddr_loc_countryRegion() {
        return this.addr_loc_countryRegion;
    }
    
    public void setAddr_loc_countryRegion(String addr_loc_countryRegion) {
        this.addr_loc_countryRegion = addr_loc_countryRegion;
    }
    @Id 
    

    @Column(name="`Addr.Loc.State`", insertable=false, updatable=false)
    public String getAddr_loc_state() {
        return this.addr_loc_state;
    }
    
    public void setAddr_loc_state(String addr_loc_state) {
        this.addr_loc_state = addr_loc_state;
    }
    @Id 
    

    @Column(name="`Addr.Loc.City`", insertable=false, updatable=false)
    public String getAddr_loc_city() {
        return this.addr_loc_city;
    }
    
    public void setAddr_loc_city(String addr_loc_city) {
        this.addr_loc_city = addr_loc_city;
    }
    @Id 
    

    @Column(name="`Addr.PostalCode`", insertable=false, updatable=false)
    public String getAddr_postalCode() {
        return this.addr_postalCode;
    }
    
    public void setAddr_postalCode(String addr_postalCode) {
        this.addr_postalCode = addr_postalCode;
    }
    @Id 
    

    @Column(name="`EMail`", insertable=false, updatable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    @Id 
    

    @Column(name="`WebSite`", insertable=false, updatable=false)
    public String getWebSite() {
        return this.webSite;
    }
    
    public void setWebSite(String webSite) {
        this.webSite = webSite;
    }
    @Id 
    

    @Column(name="`ModifiedDate`", nullable=false, insertable=false, updatable=false, length=23)
    public LocalDateTime getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(LocalDateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof VjobCandidate) )
		    return false;

		 VjobCandidate that = (VjobCandidate) o;

         return ( (this.getJobCandidateId()==that.getJobCandidateId()) || ( this.getJobCandidateId()!=null && that.getJobCandidateId()!=null && this.getJobCandidateId().equals(that.getJobCandidateId()) ) )
 && ( (this.getBusinessEntityId()==that.getBusinessEntityId()) || ( this.getBusinessEntityId()!=null && that.getBusinessEntityId()!=null && this.getBusinessEntityId().equals(that.getBusinessEntityId()) ) )
 && ( (this.getName_prefix()==that.getName_prefix()) || ( this.getName_prefix()!=null && that.getName_prefix()!=null && this.getName_prefix().equals(that.getName_prefix()) ) )
 && ( (this.getName_first()==that.getName_first()) || ( this.getName_first()!=null && that.getName_first()!=null && this.getName_first().equals(that.getName_first()) ) )
 && ( (this.getName_middle()==that.getName_middle()) || ( this.getName_middle()!=null && that.getName_middle()!=null && this.getName_middle().equals(that.getName_middle()) ) )
 && ( (this.getName_last()==that.getName_last()) || ( this.getName_last()!=null && that.getName_last()!=null && this.getName_last().equals(that.getName_last()) ) )
 && ( (this.getName_suffix()==that.getName_suffix()) || ( this.getName_suffix()!=null && that.getName_suffix()!=null && this.getName_suffix().equals(that.getName_suffix()) ) )
 && ( (this.getSkills()==that.getSkills()) || ( this.getSkills()!=null && that.getSkills()!=null && this.getSkills().equals(that.getSkills()) ) )
 && ( (this.getAddr_type()==that.getAddr_type()) || ( this.getAddr_type()!=null && that.getAddr_type()!=null && this.getAddr_type().equals(that.getAddr_type()) ) )
 && ( (this.getAddr_loc_countryRegion()==that.getAddr_loc_countryRegion()) || ( this.getAddr_loc_countryRegion()!=null && that.getAddr_loc_countryRegion()!=null && this.getAddr_loc_countryRegion().equals(that.getAddr_loc_countryRegion()) ) )
 && ( (this.getAddr_loc_state()==that.getAddr_loc_state()) || ( this.getAddr_loc_state()!=null && that.getAddr_loc_state()!=null && this.getAddr_loc_state().equals(that.getAddr_loc_state()) ) )
 && ( (this.getAddr_loc_city()==that.getAddr_loc_city()) || ( this.getAddr_loc_city()!=null && that.getAddr_loc_city()!=null && this.getAddr_loc_city().equals(that.getAddr_loc_city()) ) )
 && ( (this.getAddr_postalCode()==that.getAddr_postalCode()) || ( this.getAddr_postalCode()!=null && that.getAddr_postalCode()!=null && this.getAddr_postalCode().equals(that.getAddr_postalCode()) ) )
 && ( (this.getEmail()==that.getEmail()) || ( this.getEmail()!=null && that.getEmail()!=null && this.getEmail().equals(that.getEmail()) ) )
 && ( (this.getWebSite()==that.getWebSite()) || ( this.getWebSite()!=null && that.getWebSite()!=null && this.getWebSite().equals(that.getWebSite()) ) )
 && ( (this.getModifiedDate()==that.getModifiedDate()) || ( this.getModifiedDate()!=null && that.getModifiedDate()!=null && this.getModifiedDate().equals(that.getModifiedDate()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getJobCandidateId() == null ? 0 : this.getJobCandidateId().hashCode() );
         result = 37 * result + ( getBusinessEntityId() == null ? 0 : this.getBusinessEntityId().hashCode() );
         result = 37 * result + ( getName_prefix() == null ? 0 : this.getName_prefix().hashCode() );
         result = 37 * result + ( getName_first() == null ? 0 : this.getName_first().hashCode() );
         result = 37 * result + ( getName_middle() == null ? 0 : this.getName_middle().hashCode() );
         result = 37 * result + ( getName_last() == null ? 0 : this.getName_last().hashCode() );
         result = 37 * result + ( getName_suffix() == null ? 0 : this.getName_suffix().hashCode() );
         result = 37 * result + ( getSkills() == null ? 0 : this.getSkills().hashCode() );
         result = 37 * result + ( getAddr_type() == null ? 0 : this.getAddr_type().hashCode() );
         result = 37 * result + ( getAddr_loc_countryRegion() == null ? 0 : this.getAddr_loc_countryRegion().hashCode() );
         result = 37 * result + ( getAddr_loc_state() == null ? 0 : this.getAddr_loc_state().hashCode() );
         result = 37 * result + ( getAddr_loc_city() == null ? 0 : this.getAddr_loc_city().hashCode() );
         result = 37 * result + ( getAddr_postalCode() == null ? 0 : this.getAddr_postalCode().hashCode() );
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getWebSite() == null ? 0 : this.getWebSite().hashCode() );
         result = 37 * result + ( getModifiedDate() == null ? 0 : this.getModifiedDate().hashCode() );

         return result;
    }


}

