/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/

package com.testmssqlimport.adventureworks2014.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testmssqlimport.adventureworks2014.*;

/**
 * Service object for domain model class EmployeePayHistory.
 * @see com.testmssqlimport.adventureworks2014.EmployeePayHistory
 */

public interface EmployeePayHistoryService {
   /**
	 * Creates a new employeepayhistory.
	 * 
	 * @param created
	 *            The information of the created employeepayhistory.
	 * @return The created employeepayhistory.
	 */
	public EmployeePayHistory create(EmployeePayHistory created);

	/**
	 * Deletes a employeepayhistory.
	 * 
	 * @param employeepayhistoryId
	 *            The id of the deleted employeepayhistory.
	 * @return The deleted employeepayhistory.
	 * @throws EntityNotFoundException
	 *             if no employeepayhistory is found with the given id.
	 */
	public EmployeePayHistory delete(EmployeePayHistoryId employeepayhistoryId) throws EntityNotFoundException;

	/**
	 * Finds all employeepayhistorys.
	 * 
	 * @return A list of employeepayhistorys.
	 */
	public Page<EmployeePayHistory> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<EmployeePayHistory> findAll(Pageable pageable);
	
	/**
	 * Finds employeepayhistory by id.
	 * 
	 * @param id
	 *            The id of the wanted employeepayhistory.
	 * @return The found employeepayhistory. If no employeepayhistory is found, this method returns
	 *         null.
	 */
	public EmployeePayHistory findById(EmployeePayHistoryId id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a employeepayhistory.
	 * 
	 * @param updated
	 *            The information of the updated employeepayhistory.
	 * @return The updated employeepayhistory.
	 * @throws EntityNotFoundException
	 *             if no employeepayhistory is found with given id.
	 */
	public EmployeePayHistory update(EmployeePayHistory updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the employeepayhistorys in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the employeepayhistory.
	 */

	public long countAll();


    public Page<EmployeePayHistory> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

