/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/

package com.testmssqlimport.adventureworks2014.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/





import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testmssqlimport.adventureworks2014.*;


/**
 * ServiceImpl object for domain model class EmployeeDepartmentHistory.
 * @see com.testmssqlimport.adventureworks2014.EmployeeDepartmentHistory
 */
@Service("AdventureWorks2014.EmployeeDepartmentHistoryService")
public class EmployeeDepartmentHistoryServiceImpl implements EmployeeDepartmentHistoryService {


    private static final Logger LOGGER = LoggerFactory.getLogger(EmployeeDepartmentHistoryServiceImpl.class);

    @Autowired
    @Qualifier("AdventureWorks2014.EmployeeDepartmentHistoryDao")
    private WMGenericDao<EmployeeDepartmentHistory, EmployeeDepartmentHistoryId> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<EmployeeDepartmentHistory, EmployeeDepartmentHistoryId> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
     public Page<EmployeeDepartmentHistory> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "AdventureWorks2014TransactionManager")
    @Override
    public EmployeeDepartmentHistory create(EmployeeDepartmentHistory employeedepartmenthistory) {
        LOGGER.debug("Creating a new employeedepartmenthistory with information: {}" , employeedepartmenthistory);
        return this.wmGenericDao.create(employeedepartmenthistory);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "AdventureWorks2014TransactionManager")
    @Override
    public EmployeeDepartmentHistory delete(EmployeeDepartmentHistoryId employeedepartmenthistoryId) throws EntityNotFoundException {
        LOGGER.debug("Deleting employeedepartmenthistory with id: {}" , employeedepartmenthistoryId);
        EmployeeDepartmentHistory deleted = this.wmGenericDao.findById(employeedepartmenthistoryId);
        if (deleted == null) {
            LOGGER.debug("No employeedepartmenthistory found with id: {}" , employeedepartmenthistoryId);
            throw new EntityNotFoundException(String.valueOf(employeedepartmenthistoryId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public Page<EmployeeDepartmentHistory> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all employeedepartmenthistorys");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public Page<EmployeeDepartmentHistory> findAll(Pageable pageable) {
        LOGGER.debug("Finding all employeedepartmenthistorys");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public EmployeeDepartmentHistory findById(EmployeeDepartmentHistoryId id) throws EntityNotFoundException {
        LOGGER.debug("Finding employeedepartmenthistory by id: {}" , id);
        EmployeeDepartmentHistory employeedepartmenthistory=this.wmGenericDao.findById(id);
        if(employeedepartmenthistory==null){
            LOGGER.debug("No employeedepartmenthistory found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return employeedepartmenthistory;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "AdventureWorks2014TransactionManager")
    @Override
    public EmployeeDepartmentHistory update(EmployeeDepartmentHistory updated) throws EntityNotFoundException {
        LOGGER.debug("Updating employeedepartmenthistory with information: {}" , updated);
        this.wmGenericDao.update(updated);

        EmployeeDepartmentHistoryId id = new EmployeeDepartmentHistoryId();
        id.setBusinessEntityId(updated.getBusinessEntityId());
        id.setStartDate(updated.getStartDate());
        id.setDepartmentId(updated.getDepartmentId());
        id.setShiftId(updated.getShiftId());

        return this.wmGenericDao.findById(id);
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


