/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/

package com.testmssqlimport.adventureworks2014.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testmssqlimport.adventureworks2014.*;

/**
 * Service object for domain model class JobCandidate.
 * @see com.testmssqlimport.adventureworks2014.JobCandidate
 */

public interface JobCandidateService {
   /**
	 * Creates a new jobcandidate.
	 * 
	 * @param created
	 *            The information of the created jobcandidate.
	 * @return The created jobcandidate.
	 */
	public JobCandidate create(JobCandidate created);

	/**
	 * Deletes a jobcandidate.
	 * 
	 * @param jobcandidateId
	 *            The id of the deleted jobcandidate.
	 * @return The deleted jobcandidate.
	 * @throws EntityNotFoundException
	 *             if no jobcandidate is found with the given id.
	 */
	public JobCandidate delete(Integer jobcandidateId) throws EntityNotFoundException;

	/**
	 * Finds all jobcandidates.
	 * 
	 * @return A list of jobcandidates.
	 */
	public Page<JobCandidate> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<JobCandidate> findAll(Pageable pageable);
	
	/**
	 * Finds jobcandidate by id.
	 * 
	 * @param id
	 *            The id of the wanted jobcandidate.
	 * @return The found jobcandidate. If no jobcandidate is found, this method returns
	 *         null.
	 */
	public JobCandidate findById(Integer id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a jobcandidate.
	 * 
	 * @param updated
	 *            The information of the updated jobcandidate.
	 * @return The updated jobcandidate.
	 * @throws EntityNotFoundException
	 *             if no jobcandidate is found with given id.
	 */
	public JobCandidate update(JobCandidate updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the jobcandidates in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the jobcandidate.
	 */

	public long countAll();


    public Page<JobCandidate> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

