/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/

package com.testmssqlimport.adventureworks2014.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testmssqlimport.adventureworks2014.*;

/**
 * Service object for domain model class Shift.
 * @see com.testmssqlimport.adventureworks2014.Shift
 */

public interface ShiftService {
   /**
	 * Creates a new shift.
	 * 
	 * @param created
	 *            The information of the created shift.
	 * @return The created shift.
	 */
	public Shift create(Shift created);

	/**
	 * Deletes a shift.
	 * 
	 * @param shiftId
	 *            The id of the deleted shift.
	 * @return The deleted shift.
	 * @throws EntityNotFoundException
	 *             if no shift is found with the given id.
	 */
	public Shift delete(Byte shiftId) throws EntityNotFoundException;

	/**
	 * Finds all shifts.
	 * 
	 * @return A list of shifts.
	 */
	public Page<Shift> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<Shift> findAll(Pageable pageable);
	
	/**
	 * Finds shift by id.
	 * 
	 * @param id
	 *            The id of the wanted shift.
	 * @return The found shift. If no shift is found, this method returns
	 *         null.
	 */
	public Shift findById(Byte id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a shift.
	 * 
	 * @param updated
	 *            The information of the updated shift.
	 * @return The updated shift.
	 * @throws EntityNotFoundException
	 *             if no shift is found with given id.
	 */
	public Shift update(Shift updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the shifts in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the shift.
	 */

	public long countAll();


    public Page<Shift> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

