/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/

package com.testmssqlimport.adventureworks2014.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/





import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testmssqlimport.adventureworks2014.*;


/**
 * ServiceImpl object for domain model class Shift.
 * @see com.testmssqlimport.adventureworks2014.Shift
 */
@Service("AdventureWorks2014.ShiftService")
public class ShiftServiceImpl implements ShiftService {


    private static final Logger LOGGER = LoggerFactory.getLogger(ShiftServiceImpl.class);

    @Autowired
    @Qualifier("AdventureWorks2014.ShiftDao")
    private WMGenericDao<Shift, Byte> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Shift, Byte> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
     public Page<Shift> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "AdventureWorks2014TransactionManager")
    @Override
    public Shift create(Shift shift) {
        LOGGER.debug("Creating a new shift with information: {}" , shift);
        return this.wmGenericDao.create(shift);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "AdventureWorks2014TransactionManager")
    @Override
    public Shift delete(Byte shiftId) throws EntityNotFoundException {
        LOGGER.debug("Deleting shift with id: {}" , shiftId);
        Shift deleted = this.wmGenericDao.findById(shiftId);
        if (deleted == null) {
            LOGGER.debug("No shift found with id: {}" , shiftId);
            throw new EntityNotFoundException(String.valueOf(shiftId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public Page<Shift> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all shifts");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public Page<Shift> findAll(Pageable pageable) {
        LOGGER.debug("Finding all shifts");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public Shift findById(Byte id) throws EntityNotFoundException {
        LOGGER.debug("Finding shift by id: {}" , id);
        Shift shift=this.wmGenericDao.findById(id);
        if(shift==null){
            LOGGER.debug("No shift found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return shift;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "AdventureWorks2014TransactionManager")
    @Override
    public Shift update(Shift updated) throws EntityNotFoundException {
        LOGGER.debug("Updating shift with information: {}" , updated);
        this.wmGenericDao.update(updated);

        Byte id = (Byte)updated.getShiftId();

        return this.wmGenericDao.findById(id);
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


