/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/

package com.testmssqlimport.adventureworks2014.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/





import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testmssqlimport.adventureworks2014.*;


/**
 * ServiceImpl object for domain model class TableName.
 * @see com.testmssqlimport.adventureworks2014.TableName
 */
@Service("AdventureWorks2014.TableNameService")
public class TableNameServiceImpl implements TableNameService {


    private static final Logger LOGGER = LoggerFactory.getLogger(TableNameServiceImpl.class);

    @Autowired
    @Qualifier("AdventureWorks2014.TableNameDao")
    private WMGenericDao<TableName, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<TableName, Integer> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
     public Page<TableName> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "AdventureWorks2014TransactionManager")
    @Override
    public TableName create(TableName tablename) {
        LOGGER.debug("Creating a new tablename with information: {}" , tablename);
        return this.wmGenericDao.create(tablename);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "AdventureWorks2014TransactionManager")
    @Override
    public TableName delete(Integer tablenameId) throws EntityNotFoundException {
        LOGGER.debug("Deleting tablename with id: {}" , tablenameId);
        TableName deleted = this.wmGenericDao.findById(tablenameId);
        if (deleted == null) {
            LOGGER.debug("No tablename found with id: {}" , tablenameId);
            throw new EntityNotFoundException(String.valueOf(tablenameId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public Page<TableName> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all tablenames");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public Page<TableName> findAll(Pageable pageable) {
        LOGGER.debug("Finding all tablenames");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public TableName findById(Integer id) throws EntityNotFoundException {
        LOGGER.debug("Finding tablename by id: {}" , id);
        TableName tablename=this.wmGenericDao.findById(id);
        if(tablename==null){
            LOGGER.debug("No tablename found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return tablename;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "AdventureWorks2014TransactionManager")
    @Override
    public TableName update(TableName updated) throws EntityNotFoundException {
        LOGGER.debug("Updating tablename with information: {}" , updated);
        this.wmGenericDao.update(updated);

        Integer id = (Integer)updated.getColumn1();

        return this.wmGenericDao.findById(id);
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


