/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/

package com.testmssqlimport.adventureworks2014.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testmssqlimport.adventureworks2014.*;

/**
 * Service object for domain model class Vemployee.
 * @see com.testmssqlimport.adventureworks2014.Vemployee
 */

public interface VemployeeService {
   /**
	 * Creates a new vemployee.
	 * 
	 * @param created
	 *            The information of the created vemployee.
	 * @return The created vemployee.
	 */
	public Vemployee create(Vemployee created);

	/**
	 * Deletes a vemployee.
	 * 
	 * @param vemployeeId
	 *            The id of the deleted vemployee.
	 * @return The deleted vemployee.
	 * @throws EntityNotFoundException
	 *             if no vemployee is found with the given id.
	 */
	public Vemployee delete(VemployeeId vemployeeId) throws EntityNotFoundException;

	/**
	 * Finds all vemployees.
	 * 
	 * @return A list of vemployees.
	 */
	public Page<Vemployee> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<Vemployee> findAll(Pageable pageable);
	
	/**
	 * Finds vemployee by id.
	 * 
	 * @param id
	 *            The id of the wanted vemployee.
	 * @return The found vemployee. If no vemployee is found, this method returns
	 *         null.
	 */
	public Vemployee findById(VemployeeId id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a vemployee.
	 * 
	 * @param updated
	 *            The information of the updated vemployee.
	 * @return The updated vemployee.
	 * @throws EntityNotFoundException
	 *             if no vemployee is found with given id.
	 */
	public Vemployee update(Vemployee updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the vemployees in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the vemployee.
	 */

	public long countAll();


    public Page<Vemployee> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

