/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/

package com.testmssqlimport.adventureworks2014.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/





import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testmssqlimport.adventureworks2014.*;


/**
 * ServiceImpl object for domain model class VemployeeDepartment.
 * @see com.testmssqlimport.adventureworks2014.VemployeeDepartment
 */
@Service("AdventureWorks2014.VemployeeDepartmentService")
public class VemployeeDepartmentServiceImpl implements VemployeeDepartmentService {


    private static final Logger LOGGER = LoggerFactory.getLogger(VemployeeDepartmentServiceImpl.class);

    @Autowired
    @Qualifier("AdventureWorks2014.VemployeeDepartmentDao")
    private WMGenericDao<VemployeeDepartment, VemployeeDepartmentId> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<VemployeeDepartment, VemployeeDepartmentId> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
     public Page<VemployeeDepartment> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "AdventureWorks2014TransactionManager")
    @Override
    public VemployeeDepartment create(VemployeeDepartment vemployeedepartment) {
        LOGGER.debug("Creating a new vemployeedepartment with information: {}" , vemployeedepartment);
        return this.wmGenericDao.create(vemployeedepartment);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "AdventureWorks2014TransactionManager")
    @Override
    public VemployeeDepartment delete(VemployeeDepartmentId vemployeedepartmentId) throws EntityNotFoundException {
        LOGGER.debug("Deleting vemployeedepartment with id: {}" , vemployeedepartmentId);
        VemployeeDepartment deleted = this.wmGenericDao.findById(vemployeedepartmentId);
        if (deleted == null) {
            LOGGER.debug("No vemployeedepartment found with id: {}" , vemployeedepartmentId);
            throw new EntityNotFoundException(String.valueOf(vemployeedepartmentId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public Page<VemployeeDepartment> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all vemployeedepartments");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public Page<VemployeeDepartment> findAll(Pageable pageable) {
        LOGGER.debug("Finding all vemployeedepartments");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public VemployeeDepartment findById(VemployeeDepartmentId id) throws EntityNotFoundException {
        LOGGER.debug("Finding vemployeedepartment by id: {}" , id);
        VemployeeDepartment vemployeedepartment=this.wmGenericDao.findById(id);
        if(vemployeedepartment==null){
            LOGGER.debug("No vemployeedepartment found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return vemployeedepartment;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "AdventureWorks2014TransactionManager")
    @Override
    public VemployeeDepartment update(VemployeeDepartment updated) throws EntityNotFoundException {
        LOGGER.debug("Updating vemployeedepartment with information: {}" , updated);
        this.wmGenericDao.update(updated);

        VemployeeDepartmentId id = new VemployeeDepartmentId();
        id.setBusinessEntityId(updated.getBusinessEntityId());
        id.setTitle(updated.getTitle());
        id.setFirstName(updated.getFirstName());
        id.setMiddleName(updated.getMiddleName());
        id.setLastName(updated.getLastName());
        id.setSuffix(updated.getSuffix());
        id.setJobTitle(updated.getJobTitle());
        id.setDepartment(updated.getDepartment());
        id.setGroupName(updated.getGroupName());
        id.setStartDate(updated.getStartDate());

        return this.wmGenericDao.findById(id);
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


