/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/

package com.testmssqlimport.adventureworks2014.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/





import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testmssqlimport.adventureworks2014.*;


/**
 * ServiceImpl object for domain model class Vemployee.
 * @see com.testmssqlimport.adventureworks2014.Vemployee
 */
@Service("AdventureWorks2014.VemployeeService")
public class VemployeeServiceImpl implements VemployeeService {


    private static final Logger LOGGER = LoggerFactory.getLogger(VemployeeServiceImpl.class);

    @Autowired
    @Qualifier("AdventureWorks2014.VemployeeDao")
    private WMGenericDao<Vemployee, VemployeeId> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Vemployee, VemployeeId> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
     public Page<Vemployee> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "AdventureWorks2014TransactionManager")
    @Override
    public Vemployee create(Vemployee vemployee) {
        LOGGER.debug("Creating a new vemployee with information: {}" , vemployee);
        return this.wmGenericDao.create(vemployee);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "AdventureWorks2014TransactionManager")
    @Override
    public Vemployee delete(VemployeeId vemployeeId) throws EntityNotFoundException {
        LOGGER.debug("Deleting vemployee with id: {}" , vemployeeId);
        Vemployee deleted = this.wmGenericDao.findById(vemployeeId);
        if (deleted == null) {
            LOGGER.debug("No vemployee found with id: {}" , vemployeeId);
            throw new EntityNotFoundException(String.valueOf(vemployeeId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public Page<Vemployee> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all vemployees");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public Page<Vemployee> findAll(Pageable pageable) {
        LOGGER.debug("Finding all vemployees");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public Vemployee findById(VemployeeId id) throws EntityNotFoundException {
        LOGGER.debug("Finding vemployee by id: {}" , id);
        Vemployee vemployee=this.wmGenericDao.findById(id);
        if(vemployee==null){
            LOGGER.debug("No vemployee found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return vemployee;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "AdventureWorks2014TransactionManager")
    @Override
    public Vemployee update(Vemployee updated) throws EntityNotFoundException {
        LOGGER.debug("Updating vemployee with information: {}" , updated);
        this.wmGenericDao.update(updated);

        VemployeeId id = new VemployeeId();
        id.setBusinessEntityId(updated.getBusinessEntityId());
        id.setTitle(updated.getTitle());
        id.setFirstName(updated.getFirstName());
        id.setMiddleName(updated.getMiddleName());
        id.setLastName(updated.getLastName());
        id.setSuffix(updated.getSuffix());
        id.setJobTitle(updated.getJobTitle());
        id.setPhoneNumber(updated.getPhoneNumber());
        id.setPhoneNumberType(updated.getPhoneNumberType());
        id.setEmailAddress(updated.getEmailAddress());
        id.setEmailPromotion(updated.getEmailPromotion());
        id.setAddressLine1(updated.getAddressLine1());
        id.setAddressLine2(updated.getAddressLine2());
        id.setCity(updated.getCity());
        id.setStateProvinceName(updated.getStateProvinceName());
        id.setPostalCode(updated.getPostalCode());
        id.setCountryRegionName(updated.getCountryRegionName());
        id.setAdditionalContactInfo(updated.getAdditionalContactInfo());

        return this.wmGenericDao.findById(id);
    }

    @Transactional(readOnly = true, value = "AdventureWorks2014TransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


