/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/

package com.testmssqlimport.adventureworks2014.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testmssqlimport.adventureworks2014.*;

/**
 * Service object for domain model class VjobCandidateEducation.
 * @see com.testmssqlimport.adventureworks2014.VjobCandidateEducation
 */

public interface VjobCandidateEducationService {
   /**
	 * Creates a new vjobcandidateeducation.
	 * 
	 * @param created
	 *            The information of the created vjobcandidateeducation.
	 * @return The created vjobcandidateeducation.
	 */
	public VjobCandidateEducation create(VjobCandidateEducation created);

	/**
	 * Deletes a vjobcandidateeducation.
	 * 
	 * @param vjobcandidateeducationId
	 *            The id of the deleted vjobcandidateeducation.
	 * @return The deleted vjobcandidateeducation.
	 * @throws EntityNotFoundException
	 *             if no vjobcandidateeducation is found with the given id.
	 */
	public VjobCandidateEducation delete(VjobCandidateEducationId vjobcandidateeducationId) throws EntityNotFoundException;

	/**
	 * Finds all vjobcandidateeducations.
	 * 
	 * @return A list of vjobcandidateeducations.
	 */
	public Page<VjobCandidateEducation> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<VjobCandidateEducation> findAll(Pageable pageable);
	
	/**
	 * Finds vjobcandidateeducation by id.
	 * 
	 * @param id
	 *            The id of the wanted vjobcandidateeducation.
	 * @return The found vjobcandidateeducation. If no vjobcandidateeducation is found, this method returns
	 *         null.
	 */
	public VjobCandidateEducation findById(VjobCandidateEducationId id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a vjobcandidateeducation.
	 * 
	 * @param updated
	 *            The information of the updated vjobcandidateeducation.
	 * @return The updated vjobcandidateeducation.
	 * @throws EntityNotFoundException
	 *             if no vjobcandidateeducation is found with given id.
	 */
	public VjobCandidateEducation update(VjobCandidateEducation updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the vjobcandidateeducations in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the vjobcandidateeducation.
	 */

	public long countAll();


    public Page<VjobCandidateEducation> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

