/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/

package com.testmssqlimport.adventureworks2014.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.testmssqlimport.adventureworks2014.*;

/**
 * Service object for domain model class VjobCandidate.
 * @see com.testmssqlimport.adventureworks2014.VjobCandidate
 */

public interface VjobCandidateService {
   /**
	 * Creates a new vjobcandidate.
	 * 
	 * @param created
	 *            The information of the created vjobcandidate.
	 * @return The created vjobcandidate.
	 */
	public VjobCandidate create(VjobCandidate created);

	/**
	 * Deletes a vjobcandidate.
	 * 
	 * @param vjobcandidateId
	 *            The id of the deleted vjobcandidate.
	 * @return The deleted vjobcandidate.
	 * @throws EntityNotFoundException
	 *             if no vjobcandidate is found with the given id.
	 */
	public VjobCandidate delete(VjobCandidateId vjobcandidateId) throws EntityNotFoundException;

	/**
	 * Finds all vjobcandidates.
	 * 
	 * @return A list of vjobcandidates.
	 */
	public Page<VjobCandidate> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<VjobCandidate> findAll(Pageable pageable);
	
	/**
	 * Finds vjobcandidate by id.
	 * 
	 * @param id
	 *            The id of the wanted vjobcandidate.
	 * @return The found vjobcandidate. If no vjobcandidate is found, this method returns
	 *         null.
	 */
	public VjobCandidate findById(VjobCandidateId id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a vjobcandidate.
	 * 
	 * @param updated
	 *            The information of the updated vjobcandidate.
	 * @return The updated vjobcandidate.
	 * @throws EntityNotFoundException
	 *             if no vjobcandidate is found with given id.
	 */
	public VjobCandidate update(VjobCandidate updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the vjobcandidates in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the vjobcandidate.
	 */

	public long countAll();


    public Page<VjobCandidate> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

